.TH NETCONTROL 1 "19 Jan 2024" "version 1.0" "User Manuals"

.SH NAME
netcontrol \- einfaches Netzwerküberwachungstool

.SH SYNOPSIS
.B netcontrol
[OPTION]... [ARGUMENT]...

.SH DESCRIPTION
Ein Bash-Skript, das grundlegende Netzwerküberwachungsfunktionen bietet. Es ermöglicht das Hinzufügen, Löschen und Anzeigen von Hosts in einer Liste und überwacht diese Hosts durch periodisches Anpingen.

.SH OPTIONS
.TP
.B addhost [hostname]
Fügt einen neuen Host zur Überwachungsliste hinzu.

.TP
.B delhost [hostname]
Entfernt einen Host aus der Überwachungsliste.

.TP
.B printhosts
Zeigt alle in der Überwachungsliste gespeicherten Hosts an.

.TP
.B install [minute]
Installiert bzw. aktualisiert einen Crontab-Eintrag, um das Skript alle [minute] Minuten auszuführen.

.TP
.B uninstall
Entfernt den Crontab-Eintrag des Skripts.

.TP
.B config
Öffnet den nano Editor um die Config Datei zu bearbeiten.

.TP
.B log
Öffnet den nano Editor um die Logs anzusehen.

.TP
(keine Option)
Die Hosts werden angepingt.

.SH FILES
.TP
.I usr/share/netcontrol/config.sh
Konfigurationseinstellungen für Anzahl der Ping-Versuche, Timeout und Intervall zwischen Pings.

.TP
.I usr/share/netcontrol/log.log
Log Datei für fehlgeschlagene Ping Versuche

.TP
.I usr/share/netcontrol/hosts
Liste der Hosts die gepingt werden sollen

.SH ENVIRONMENT
Das Skript verwendet eine Konfigurationsdatei, die im selben Verzeichnis wie das Skript gespeichert ist, um bestimmte Einstellungen zu definieren, die für das Anpingen der Hosts verwendet werden.

.SH REQUIREMENTS
Das Skript erfordert Bash und Ping-Befehlszeilentools. Es sollte auf den meisten Linux- und UNIX-basierten Systemen funktionieren.

.SH AUTHOR
Tim Burke-Lehmann

.SH "SEE ALSO"
.BR ping(8),
.BR cron(8),
.BR bash(1)
